### ISSUE TITLE
off/unbind: splice inside forEach will prevent entire cycle

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1007]
the `off`/`unbind` code splices the event array inside a `forEach` loop cycling same array: https://github.com/flowplayer/flowplayer/blob/14388e1a9902dd08886621140fafe2becf65475f/lib/ext/events.js#L62-L65

``` js
registererHandlers.forEach(function(hndlr) {
  elem.removeEventListener(actualEvent, hndlr);
  registererHandlers.splice(registererHandlers.indexOf(hndlr), 1);
});
```

This doesn't cycle through all handlers, does it?

See: https://flowplayer.org/forum/#!/scripting_api:unbind-event-doesnt-work

**Comment by vinh0604** [comment]
This issue is also causing memory leak in our angular code. We have a wrapper directive for flowplayer which has a similar controller like this:

```javascript
controller: function($scope) {
  var controller = this;
  var flowplayerObject = flowplayer("#video-container", config).on("ready", function () {
    controller.foo();
  });

  $scope.$on("$destroy", function() {
    flowplayerObject.off("ready");
    flowplayerObject.shutdown();
  });
}
```

Because the `ready` handler is not cleaned up when calling `off`, our controller instance is not destroyed by GC and stay in memory even after the directive is destroyed.

Another issue is that `shutdown` not removing those event handlers internally, so memory leak still happens if we don't call `off` explicitly.

Thanks.

**Comment by nnarhinen** [comment]
@bbbo how does #1086 look like to you?

**Comment by blacktrash** [comment]
I trust you on that one - side note: `filter` is not supported by IE8.

**Comment by nnarhinen** [comment]
That's why we polyfill it.
