### ISSUE TITLE
Fullscreen doesn't work properly in under Jellybean's default browser

### ISSUE THREAD

**Issue by marufactory2** [flowplayer/flowplayer#1033]
Hello,

when I click the fullsceen button at the first time. it works fine but it doesn't work at second time.
I mean after return the screen size back and click the fullscreen button again. it doesn't work.
This error occurs only in Jellybean's default browser. In Chrome it works fine.
How can I fix it?

**Comment by nnarhinen** [comment]
All of the 4.x devices I could access lack support of fullscreen in the native browser. This is most likely once again an instance  of many Android fragmentation issues - problem with specific vendor and specific OS version. I deem this as "Notfix" but of course if some one provides a fix and the fix is easy and does not break anything for other devices it can be considered.
