### ISSUE TITLE
Built-in UI for quality selection menu

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1080]
We will have an UI in the core player for quality selection. Engines and/or plugins will tell the core player about available qualities and current  quality in `ready` event. If there are more than 1 quality, the player will show the quality selection menu. When a user changes the quality by interacting with the menu (or calling the API) an event `quality` will be raised with the selected quality as payload.

Specs:

### `ready` event

Payload (`video` argument):

```js
{
  sources: [...],
  qualities: ['480p', '720p', '1080p'],
  quality: '720p'
}
```

Or with labels:

```js
{
  sources: [ ... ],
  qualities: [{ value: -1, label: 'Auto' }, { value: 0, label: 'Lo-fi' } , { value: 1, label: 'HD' } ],
  quality: -1
}
```

### `quality` event

```js
api.on('quality', function(ev, api, quality) {
   console.log(quality);
  // for intance '720p' if qualities designed as simple string array
  // or the value of the quality object in qualities object array
});
```

### `api.quality()` method

```js
api.quality(-1); // Would fire the event `quality` with payload `-1`
```

**Comment by blacktrash** [comment]
afaics we need something like startQuality, certainly for playlists.

**Comment by blacktrash** [comment]
If we do this, it should take care of scenarios like in this demo: http://demos.flowplayer.org/api/hlsjs.html#hlsjsvod
a) if hlsjs engine is supported hls level selection is preferred, qualities are selected within one engine, and actually from one source (the master)
b) otherwise VOD/Auto qsel where qualities mean: different sources, load, ready etc. events, and, in the case of flash hls even engine switches

So under the hood the mechanism _and_ the options have to take care of fundamentally differing scenarios:
a) and b) most of the time differ
- in the amount of qualities they offer
- in the values of qualites they offer

Structurally we have for:
- hlsjs: qualities as _engine_ or _source_ option - engine is capable of detecting available qualities *before* ready (when manifest is parsed), quality selection can in principle be enabled with a simple boolean switch (in practice often not desireable because too many qualities would be on offer)
- core: qualities as _clip_ option (like in your proposal) - available qualities *must* be configured in an array etc.

The problem will be how to merge this into one (if at all possible), because we lie about the underlying mechanism for ease of use (good thing if it really can be done).

The difference is also in the base of notation:
- hlsjs: number (index) based, extensible to object - the latter even required when the qualities differ only by bit rate, not resolution (although that could happen for VOD/Auto too *if* we at some point want to be independent of file naming etc. constraints)
- VOD/Auto: currently String based - only possible because of strict flilename layout requirements, would require complex configuration otherwise (differing src even by type possible etc.)

Similarly for the quality event:
1. it probably wants to be split up into 2: a beforeQuality event when the quality is _selected_, and the actual quality event, when the quality is loaded
2. the user facing quality event internally maps to fundamentally differing scenarios. hlsjs: a level (including Auto) of the same master is played, no ready etc. involved; VOD/Auto: a different clip is loaded with all that entails, including a potential engine switch

**Comment by nnarhinen** [comment]
We can leave out all the internal stuff of HLS engines (automatic level switches of flashls and hlsjs).

The beauty (in my opinion) of this proposed approach is
 * Zero configuration if engine has support of qsel baked in (like the flash(ls) engine now has)
 * Qualities are only reported in `ready` event
 * The core UI & API only trigger the `quality` event - leaves the hard work to plugins / engines.

**Comment by nnarhinen** [comment]
We will adapt our (VOD) quality selector plugin to this. All user interaction logic and UI element code can be removed.

 * It will take over quality selection duties from engines (we maybe need a **source** property for this, like `qsel: false`)
 * It will extend the video object at `load` so that it has the qualities in `ready` (as string array)
 * It will listen to the `quality` event and then do the `load()` magic to choose correct url

**Comment by nnarhinen** [comment]
I think this also makes it easier to create a general purpose (not dependant of file layout) qsel plugin.

It's configuration could look like this:

```js
flowplayer('#myplayer', {
  clip: {
    sources: [...],
    myQselPluginQualities: [{
      label: '480p',
      src: '//myserver.com/standard.mp4'
    },
    {
      label: '720p',
      src: '//myserver.com/hd.mp4'
    },
    {
      label: '1080p',
      src: '//myserver.com/fullhd.mp4'
    }
  }
});
```

Then the plugin would convert that into the form the player UI expects in `ready` event:


```
{
  sources: [...],
  qualities: [{ label: '480p', value: 0 }, { label: '720p', value: 1 } , { label: '1080p', value: 2 }]
}
```

**Comment by nnarhinen** [comment]
I guess the default quality could be chosen by the qsel plugin. I have not thought this through yet from the plugin perspective. The same goes for our current VOD qsel plugin, not ready yet.

**Comment by blacktrash** [comment]
I'm all for unifying this, and phantastic that it's even gonna work with Flash HLS.
Just so you know, the hlsjs plugin can send available qualities even before ready - in case there's a situation where this is useful.

**Comment by nnarhinen** [comment]
`ready` is good, IMO. That's when we remove loading indicator and show UI.

**Comment by blacktrash** [comment]
afaics we still need `hlsQualities` or something similar. http://demos.flowplayer.org/api/hlsjs.html#hlsjslive shows why, and also why I chose a boolean to show all available levels _without_ filtering.
This is how the manifest looks like:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=563000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_400_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=563000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_400_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=827000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_700_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=827000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_700_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2128000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_1000_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2128000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://nasatv-lh.akamaihd.net/i/NASA_101@319270/index_1000_av-b.m3u8?sd=10&rebase=on
```
1. all levels have the same resolution, so filtering on same resolution would have not the intended effect
2. 3 streams are so-called [redundant streams](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW22) - sort of HLS clustering - and want to be omitted as candidates for manual selection; hls.js recognizes them and returns only 3 levels: `flowplayer(1).engine.hlsjs.levels.length` yields `3` (don't know how our flash hls implementation behaves)

which yields to the following hlsQualities config:
```js
hlsQualities: [
  { level: 0, label: "563k" },
  { level: 1, label: "828k" },
  { level: 2, label: "2128k" }
]
```
What hlsjs _could_ do for automation (provided the master playlist has the info) is to send labels with the BANDWIDTH values like above.

**Comment by blacktrash** [comment]
Note that automating same resolution -> fail over to bit rate would create labels with mixed units e.g. for Drive videos. For Drive videos we could also say: fail over to bit rate in *any* duplicate resolution is encountered, but this would again yield same labels for manifests where there are duplicate resolutions *and* also duplicate bit rates.
That's the reason why I decided to leave this to the user - except for the `hlsQualities: "drive"` proposal where we know how the levels behave.

**Comment by nnarhinen** [comment]
The bandwidths do not really tell the end-user anything useful. Even I would not know anything about "536k" vs "828k" if shown in a video player UI.

I'd say the default behavior will be to show quality selection menu with different resolutions. If there's only one resolution the menu won't appear.

Then we add the ability to provide `hlsQualities` as in your config example:

```
hlsQualities: [
  { level: 0, label: 'Low quality' },
  { level: 1, label: 'Normal quality' },
  { level: 2, label: 'High quality' }
]
```

**Comment by blacktrash** [comment]
That's fine because we will now have a menu heading, correct? - I could not do this in the demo because the current menu doesn't give enough horizontal space, and if the new menu does, it will be a problem most likely on mobiles, but "High" etc. with a "Quality" or similar heading would do it.

Can I convince you to keep the boolean for hlsQualities? I can make the hlsjs plugin send the full array or null or whatever is needed. `true` is useful for users to quickly check in a "GUI" what and how many qualities are available, `false` or null? is good to turn off selection for specific clips if you set hlsQualities on player level or globally otherwise.

**Comment by nnarhinen** [comment]
It will be `true` by default at least for flashls.

**Comment by blacktrash** [comment]
ok, I will adapt the defaults for hlsjs.

**Comment by blacktrash** [comment]
hang on, so: `true` means with same resolutions filtered out?

**Comment by nnarhinen** [comment]
Yes, the default is to show the qsel menu always when HLS is used and multiple resolutions can be automatically extracted.

**Comment by blacktrash** [comment]
hm - as shown filtering by default is somewhat biased towards our manifests; may be then have an option like "all".

**Comment by blacktrash** [comment]
Is "Auto" available for customization?
UI and label aspect:
- If yes (pro: localization) is it mandatory to be put in config (see next) at least the value or does the omission mean `{value: -1, label: "Auto"}`?
- Conceivably someone may want a player with manual hls level switching ...

Technically:
- core should fix/deal with https://github.com/flowplayer/flowplayer-quality-selector/issues/13
- will "Auto" become part of the api.qualities array? It is not with current quality selector, "abr" api.quality is handled "separately".

**Comment by nnarhinen** [comment]
As I don't really understand what you're asking, maybe better if you take a look yourself:

https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/qsel.js#L41-L52

The UI only works with the `video.qualities` array on `ready` event. And the engine / plugin is responsible of feeding that array to `video` object.

**Comment by nnarhinen** [comment]
This is the Flash(ls) engine part of the qualities feeding: https://github.com/flowplayer/flowplayer/blob/2d505c8c9be74c9f80e5cfff0637ef3e576513c7/lib/as/HLSStreamProvider.as#L173-L193

**Comment by blacktrash** [comment]
OK, afaics each engine is in charge of creating value-label pairs.
And so far the "Auto" label is hard-coded, and not configurable, entirely depending on whether ABR is present.

**Comment by blacktrash** [comment]
@nnarhinen - https://github.com/flowplayer/flowplayer/blob/2d505c8c9be74c9f80e5cfff0637ef3e576513c7/lib/as/HLSStreamProvider.as#L174
imho this must change in a playlist if we want to keep existing quality-selector and hlsjs behavior: if the current quality (of the previous clip) is available, it should be loaded right away (in hls.js: startLevel); otherwise it's annoying with a playlist of short clips.
Unfortunately it may be somewhat harder to do with flash hls, see the `startfrombitrate` and `startfromlevel` params: https://flowplayer.org/docs/setup.html#flashls

**Comment by blacktrash** [comment]
afaics https://github.com/flowplayer/flowplayer/blob/2d505c8c9be74c9f80e5cfff0637ef3e576513c7/lib/as/HLSStreamProvider.as#L173-L193 assumes that width, height, and bitrate are given in manifest?
This may not be the case. In the worst case scenario none is given, and there should be a failover label, in hlsjs I currently use `Level {index + 1}`.

**Comment by blacktrash** [comment]
If there's only 1 level available, there should not be a menu entry: http://flowplayer.blacktrash.org/fp7/live.html

**Comment by blacktrash** [comment]
Here's what I mean re: start level: http://flowplayer.blacktrash.org/fp7/playlist.html
quality goes back to ABR at start of each clip, regardless of whether I picked a fixed quality before.

**Comment by nnarhinen** [comment]
Can you make http://flowplayer.blacktrash.org/fp7/live.html use the dev assets?

**Comment by blacktrash** [comment]
@nnarhinen - done

**Comment by blacktrash** [comment]
removal of HD menu works ;-)
