### ISSUE TITLE
Fullscreen button doesn't do anything on Safari / Mac

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1191]
Safari v 10.0.3
OSX 10.12.3

Clicking the fullscreen icon here has no effect: http://demos.flowplayer.org/basics/minimal.html

**Comment by blacktrash** [comment]
@nnarhinen - FWIW, I don't have 10.0.3 (only 10.1), but in Browstack there happens to be a 10.0.3, and:
- http://demos.flowplayer.org/basics/minimal.html does not work
- http://demos.flowplayer.org/v6/basics/minimal.html works

**Comment by blacktrash** [comment]
Same with 9.1 - needs cross-testing on real machines.

**Comment by nnarhinen** [comment]
Seems to work here, also removed one old safari hack, should not be needed anymore.

**Comment by tadegunloye** [comment]
@nnarhinen It seems like this issue came up again. After updating to macOS Mojave (10.14.5) with Safari V. 12.1.1, this same behavior returned. I tested this on Flowplayer 6, 7, and the current flowplayer version. 

I also tested on the demo sites mentioned in this thread and found the same issue there.
