### ISSUE TITLE
API : video object properties are not updated in HLS

### ISSUE THREAD

**Issue by fvilpoix** [flowplayer/flowplayer#1200]
Hi,

I found that when I change the HLS quality (manually or programmatically), the API always returns the very first width/height of the video clip :

![image](https://cloud.githubusercontent.com/assets/1503147/26733105/14aa44d0-47ba-11e7-8705-560e744ce1b7.png)

I tried on the [HLS plugin demo page](https://flowplayer.org/standalone/plugins/hlsjs.html), with chrome/firefox last version on Ubuntu 16.04

Is there any other way to get the size of the actual file ?

Thanks a lot !

**Comment by blacktrash** [comment]
That is because only the hlsjs plugin provides detailed level information, native HLS does not, the same as there is no native manual quality switch (no JavaScript interface). For the latter you can however query the size of the video element, for the former use the api of the hlsjs plugin.
This demo http://demos.flowplayer.org/api/hlsjs.html does exactly that for the VOD example, check the code here: http://demos.flowplayer.org/api/hlsjs.html#javascript-setup

Please consider asking usage questions in our public forum at https://flowplayer.org/forum/ - they are of common interest, and therefore that's only fair towards other users. Thank you.

**Comment by fvilpoix** [comment]
Thank you for your answer, the trick does the job.

But I still see it as a bug or a feature request. In my opinion, engines are just abstraction layer to handle different video formats, and the public API should provide a unified interface to get data elements regardless of the engine.

```javascript
var height = api.video.height;
```

is far better and maintenable than

```javascript
if (hls) {
  // do long stuff
} else if (dash) {
 // do a different long stuff
} else {
  var height = api.video.height;
}
```

**Comment by blacktrash** [comment]
I agree entirely from the consistency point of view.
However, in practice, the progress event is already expensive, it's fired every 250ms, and swith the hlsjs (especially, because it does complete remuxing) and dash engines this risks to affact performance imho. Even using less frequent engine specific events for updating comes at a price. That's why we don't point blank replicate all hls.js or dashjs events as player events, see e.g.: https://github.com/flowplayer/flowplayer-hlsjs/issues/29 - I certainly like this from a consistency point of view either.

The consistency of information is limited anyway because the MSE engines by nature can provide much more information due to their required extra work.

Re-opening for comment, @nnarhinen.

**Comment by fvilpoix** [comment]
Indeed, the hlshjs library is a bit verbose :)
Of course it's a bad idea to propagate internal events of sub-libraries threw flowplayer, and it's not its job as long as the engines are accessible.

But for data related directly to the media that are accessible from flowplayer, maybe it worths the event subscription to update it in flowplayer. I think about video width/height/bitrate, which changes on hls/dash quality switch only, but perharps there are others.

**Comment by blacktrash** [comment]
bitrate is not available in native HLS ;-)

**Comment by blacktrash** [comment]
Leaving aside Flash HLS:
- video width and height can be updated in the progress event by querying `videoWidth` and `videoHeight` of the video tag
- both hls.js and dash.js provide listeners for the actual change[1] and thus the possibility to update at a lower frequency

@nnarhinen - what do you prefer:
1. update in progress evens as long engine is not Flash
2. update in progress event for native HLS (html5 engine only), use engine specific listeners otherwise


[1]
- hls.js: [LEVEL_SWITCHED](https://github.com/video-dev/hls.js/blob/master/doc/API.md#runtime-events)
- dashjs: [QUALITY_CHANGE_RENDERED](http://cdn.dashjs.org/v2.4.1/jsdoc/MediaPlayerEvents.html#event:QUALITY_CHANGE_RENDERED)

**Comment by nnarhinen** [comment]
For flashls there is `HLSEvent.LEVEL_SWITCH` which we could listen to. But for native html5 there is no such event. I think for now the best way would be to query `videoWidth` and `videoHeight` when needed. The engines can of course update `video.height` and `video.width` whenever applicable but for html5 engine some timer would be needed and it IMO adds unnecessary overhead as the information is queryable if needed.

**Comment by blacktrash** [comment]
@nnarhinen - as per https://github.com/flowplayer/flowplayer/issues/1200#issuecomment-306141914 I agree.

**Comment by nnarhinen** [comment]
I'll move this to the 7.2 milestone. Let's see if we come with a decent approach for that.
