### ISSUE TITLE
vast ads with overlay plugin doesn't work when reopening overlay

### ISSUE THREAD

**Issue by zivni** [flowplayer/flowplayer#1207]
I have a setup with overlay and vast.

When I open the overlay for the first time, everything works fine: I see the commercial and then the video. 

But if I use the Esc key before the commercial finish playing, and then open the video again, the player get stuck. 

see the demo here:  http://player.ynet.co.il/fp74/video_test_ziv.html. click on "press here", then wait for the commercial to start, press the Esc keyboard key, and then click on "press here" again.

this is my code:
```
<script>
	flowplayer.conf = {
				key: '...',
				ima : {
					adRules: "..."
				}
			};
</script>
<div id="overlay" style="cursor:pointer">
	press here
</div>
<div id="player"></div>

<script>
	const container=document.getElementById("player");
	 const settings = {
		overlay: "#overlay",
		clip: {
			sources: [
				{ type: "application/x-mpegurl",
					src:  "//cdn.flowplayer.org/202777/161579.m3u8" },
				{ type: "video/mp4",
					src:  "//cdn.flowplayer.org/202777/161579.mp4" }
			]
		}
	};
	const api= flowplayer(container, settings);
```

**Comment by blacktrash** [comment]
Some issue in the collaboration of keyboard enabled with the vast and overlay plugins.
We'll look into it.
Meanwhile you can set `keyboard: false`, and add the `is-closeable` class to the container to obtain consistent behavior.

**Comment by zivni** [comment]
The problem occurs also when using the `unload()` method of the API.

I see that  `is-closeable` is added by default for overlay. But it doesn't add a close button during commercial play. 

What I wanted is that the users can close the overlayed video also during the commercial. So I added my own button for closing, calling `unload()`. Is this the right method for closing the overlay?

See the demo here: http://player.ynet.co.il/fp74/video_test_ziv_002.html. after opening the video, wait of the commercial to play, and click the "close" text (which calls the unload method). then try playing the video again.

**Comment by blacktrash** [comment]
I doubt that this will help. `unload()` also doesn't work reliably with VAST in other (rare) circumstances: http://demos.flowplayer.org/ads/vast.html - start playback, hit `q` to unload during ad playback, click on other playlist item.
As you can see in the latter example, the playlist UI disappears during ad playback; that's intentional, it also doesn't appear when you use a default playlist layout inside the container; makes sense UI-consistency wise, but it also would lead to problems if the items were visible to click.
In theory the VAST code does a clean job of destroying the IMA instance on unload, but as usual there may be some weird timing issues. imho this can be only solved in the VAST plugin, hopefully.
For your specific case, be aware that most likely we won't add the close button to the ads UI; we had to clutter the controlbar already by moving the fullscreen button into it. The header element which normally appears on hover overlays ad widgets (more info etc.) and makes them no-ops, and creative publishers do not appreciate that.

**Comment by zivni** [comment]
Is this something that you plain to solve in the VAST plugin sometime soon?

**Comment by zivni** [comment]
I found a solution. If instead of using adRules, I'm using the ads array, there is no problem.

**Comment by blacktrash** [comment]
@zivni - thank you for your persistence. This will hopefully help us more to improve the situation on the VAST plugin side.
Closing this here, but not forgetting ;-)
