### ISSUE TITLE
Wrong duration on wowza streams

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1318]
Continuing from https://github.com/flowplayer/flowplayer-hlsjs/issues/103#issuecomment-354428967

From http://web-0.radioradicale.it/prova/fp/audio.html :

![image](https://user-images.githubusercontent.com/265438/34441927-730c1050-ecc7-11e7-80ac-809dc3cec26a.png)

**Comment by fdambrosio** [comment]
thanks! I'll test it soon!

**Comment by fdambrosio** [comment]
how can I test the new 7.2.2 release using the fixed hlsjs-lite-engine?

**Comment by bbbo** [comment]
https://releases.flowplayer.org/7.2.2/flowplayer-7.2.2.zip
resp.
https://releases.flowplayer.org/7.2.2/flowplayer.min.js
with
https://releases.flowplayer.org/7.2.2/skin/skin.css

**Comment by fdambrosio** [comment]
thanks @bbbo but if I add
https://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.min.js
duration is wrong , if I don't add hlsjs plugin the player fails because of Flash browser block 
test http://web-0.radioradicale.it/prova/fp/audio.html 
related issue https://github.com/flowplayer/flowplayer-hlsjs/issues/103

**Comment by bbbo** [comment]
Try using the hlsjs-lite engine with hls.light.min.js (not properly documented yet, docs will be added to the main setup docs soon):

http://stylebites.de/fp7/duration.html

I'm not sure if and when the hlsjs plugin will be updated.
