### ISSUE TITLE
Cuepoints marker are not removed when deleting cuepoint

### ISSUE THREAD

**Issue by fvilpoix** [flowplayer/flowplayer#1348]
Hi here,

If I'm using `generate_cuepoints` option to add cuepoints' markers on timeline, they are not removed when I use `removeCuepoint` function, but the internal list of cuepoints is well updated.

I manually remove it from DOM, but it would be nice if it was automaticaly done

**Comment by nnarhinen** [comment]
This is now fixed in the dev branch, will be part of next release.

The fix however comes with a change that might not be backwards compatible:

`api.removeCuepoint()` now  expects the whole cue object (from `api.cuepoints`) or the **internal** `index`.

`api.addCuepoint()` now generates an `index` for every cuepoint which can then be used to identify cuepoints generated dynamically.
