### ISSUE TITLE
subtitles not working on IE8

### ISSUE THREAD

**Issue by tipiirai** [flowplayer/flowplayer#31]
http://d.pr/i/irm7

**Comment by wajeeha-khalid** [comment]
Hey i am trying to run a local srt file in track element with kind="subtitles"; but the subtitles are not appearing on IE10. It does not seem to be a CORS problem

**Comment by bbbo** [comment]
I don't think IE does (and eever will) support srt. http://msdn.microsoft.com/en-us/library/ie/hh772556(v=vs.85).aspx

**Comment by nnarhinen** [comment]
@wajeeha-khalid instead of commenting on an (very) old already resolved issue, please read our https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md document and continue this discussion on our public support forum, including a link to a page where flowplayer misbehaves (if the content cannot be publicly available, create a replica with our demo videos or such).

@bbbo FP5 does not check what type the subtitles are but always parses them as WebVTT. So depending on the srt file it might just work (works at least on our own demo-section: http://demos.flowplayer.org/basics/subtitle.html)
