### ISSUE TITLE
window.onload doesn't work on iPad

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#450]
Here's a demo site: http://lifeinamovie.com/html/window-load.html

It uses //releases.flowplayer.org/5.4.2/flowplayer.min.js

Below the video these messages should appear as the JavaScript event hooks are fired:

"jQuery(document).ready fired!
jQuery(window).load fired!
window.onload fired!"

On iPad ("Mozilla/5.0 (iPad; CPU OS  5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3"), only the first appears (document ready).

The window.onload is simply not fired and its jQuery equivalent doesn't work either.

**Comment by lufes** [comment]
The problem is related to the window.onload event, which will not be triggered if there's a video with the preload="none" attribute set. window.onload will run once every asset is loaded, and iOS 8 keeps waiting for the video to load, which will never do. Only happens in iOS 8. Submitting a ticket to Apple right now.
