### ISSUE TITLE
Using multiple .m3u8 streams in horizontal scrollable

### ISSUE THREAD

**Issue by welshchris** [flowplayer/flowplayer#759]
I'm trying to develop a page to show multiple live webcam streams in a scrollable fashion using the example at http://demos.flowplayer.org/playlist/scrollable-jquerytools.html

I'm struggling with replacing the playlist code below to suit my own filenames. Can somebody tell me if it's possible to achieve what I'm trying to do and also help me to build a playlist using my .m3u8 file url's? - clearly the streams are 'never ending' so there'd be no need to switch to the next video as the current file has finished playing as in the demo.

// for testing only, do not use this switch in production!
flowplayer.conf.engine = /flash/.test($(location).prop("search")) ? "flash" : "html5";
$(function () {
  var playlist = [],
      base = "http://stream.flowplayer.org/night",
      videos = $(".scrollable span"),
      scrollable,
      api,
      i;

  // build playlist from videos named night1 thru night6
  for (i = 1; i < 7; i = i + 1) {
    playlist.push([
      { mpegurl: base + i + ".m3u8" },
      { webm: base + i + ".webm" },
      { mp4:  base + i + ".mp4" },
      { flash: "mp4:night" + i }
    ]);
  }

**Comment by blacktrash** [comment]
@welshchris - this is a bug tracker, for usage question please go to our forum at https://flowplayer.org/forum/
The code is just to save typing, you can just write out a JavaScript playlist: https://flowplayer.org/pricing/#flowplayer-flash (you need an RTMP stream address too, unless you only want to show this where HLS is supported):
```js
var playlist = [[
  { mpegurl: "http://example.com/first.m3u8" },
  { flash: "firststream" }
], [
  { mpegurl: "http://example.com/second.m3u8" },
  { flash: "secondstream" }
]];
```
You can set `advance: false` in the player config, but it should not matter because your streams don't finish anyway.
Closing.
