### ISSUE TITLE
multiple players in iframes on the same page fail after more than 5 on chrome

### ISSUE THREAD

**Issue by kellyrmilligan** [flowplayer/flowplayer#764]
I have a custom embed page that we're putting on third party pages via an iframe.  up to 5 iframes, the player works as expected. the 6th player however, when you click on it, the request for loading the video takes ages and may never start.

**Comment by nnarhinen** [comment]
As per our [Contribution guidelines](https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md) please ask these kind of usage questions on our [support forum](https://flowplayer.org/forum/).

Also always link to an example page where the player misbehaves. Preferably stripped to a minimal reproducable case.

**Comment by kellyrmilligan** [comment]
My bad. I ended up finding an article on the forum about this. Just in case anyone ends up here, as of this writing I ended up switching to splash setup and having flow player inject the video element rather than havin it on the page already. I set what would normally be the poster on a parent element.

**Comment by blacktrash** [comment]
@kellyrmilligan - you might be able to make use of the skin CSS (with responsiveness etc.) without a parent element then. The API does not act via automatic install on an element with `class="flowplayer"` if there is no video tag inside. The - otherwise problematic - demo http://demos.flowplayer.org/scripting/signed-ondemand.html#html-setup uses that trick.
All the more a reason to ask this in our public forum, so others can profit from the answers too ;-)
