### ISSUE TITLE
Player with preload="none" freezes if you pause it before the video is loaded

### ISSUE THREAD

**Issue by bliof** [flowplayer/flowplayer#796]
When you start a video that has `preload="none"` and then immediately pause it, it won't start again.

Here is a demo: (either click the button or you could even click fast on the video but disable your cache from the console)

https://jsfiddle.net/yvrvvfp7/1/embedded/result/

https://jsfiddle.net/yvrvvfp7/1/

## The demo

``` html
<div class="flowplayer" data-ratio="0.4167">
   <video preload="none">
       <source type="video/webm" src="//stream.flowplayer.org/bauhaus.webm">
       <source type="video/mp4"  src="//stream.flowplayer.org/bauhaus.mp4">
   </video>
</div>
       
<button id="test">Fast play() and pause()</button>
```

``` javascript
$('#test').click(function() {
    var f = $('.flowplayer').data('flowplayer');
    f.play();
    f.pause();
});
```

https://releases.flowplayer.org/5.5.2/flowplayer.min.js
https://releases.flowplayer.org/5.5.2/skin/minimalist.css

**Comment by bbbo** [comment]
> When you start a video that has |preload="none"| and then immediately 
> pause it, it won't start again.
>
> Here is a demo: (either click the button or you could even click fast 
> on the video but disable your cache from the console)
>
> https://jsfiddle.net/yvrvvfp7/1/embedded/result/
>
> https://jsfiddle.net/yvrvvfp7/1/
>
>
cannot reproduce; starts again for me in every browsers I tested. Which 
OS browser?

**Comment by bliof** [comment]
I've tested on osx with chrome, safary, firefox and with virtualbox on debian and couple of windows machines with chrome / firefox. There is a button on the test page that does `play()` and `pause()` and it works 100% of the time.

The way I've patched it to check if there is `api.video.duration` in [api.pause](https://github.com/flowplayer/flowplayer/blob/master/lib/flowplayer.js#L293)

**Comment by nnarhinen** [comment]
`api.play()` is async.

I guess this does what you are after: https://jsfiddle.net/zn72u3qb/

(code):

```js
$('#test').click(function() {
    var f = $('.flowplayer').data('flowplayer');
    f.bind('ready', function() {
        f.pause();
    });
    f.play();
});
```

**Comment by bliof** [comment]
You could brake the player by clicking twice on it..

**Comment by bliof** [comment]
![flowplayer](https://cloud.githubusercontent.com/assets/540562/7765704/c87f3d02-0069-11e5-95bf-f610196c6b90.gif)

Here is gif of what happens.. but you simply click twice and it's dead

**Comment by nnarhinen** [comment]
The quality of that gif is so poor I can't see which fiddle you are clicking twice and where.

Anyway. Please move this conversation to our [support forum](https://flowplayer.org/forum/). If there actually is a valid API use case that is broken (with the current 6.0.0 code base) you or our support personnel can open a new issue about it.

It seems you have some scripting needs and need help with them. `api.play()` is async so you need to do subsequent API calls in a callback. You can get usage help from our forums.

**Comment by bliof** [comment]
Well the scripting is for you to see the problem.. Otherwise you could click twice on the video (first is `api.play()` then is `api.pause()`). I'll try 6.0.0. I had problems yesterday. That is I've used the same html as above but with the new version and it.. broke, it shows only loading dots after initialization :/

**Comment by bliof** [comment]
ps. here is the video https://www.dropbox.com/s/ad7o12xgaice7pi/flowplayer.mp4?dl=0

**Comment by bbbo** [comment]
I still cannot reprdouce. pause / resume works in FF 38, Chrome 43, IE9, 
IE10 on Win7 without problems. With cache enabled or disabled, either 
cllcking the player area very fast or using the button.

**Comment by mitio** [comment]
I was also able to reproduce this as @bliof has described it in Google Chrome (Version 43.0.2357.65 (64-bit)) on OS X. I used his JSFiddle test.

To reproduce:

1. I loaded the page.
2. I opened developer tools, clicked on "Disable cache" in the "Network" tab and reloaded again.
3. I made a quick double-click on the video. Yes, it's actually a double-click.

You can also try [limiting the network speed via the Chrome's developer tools](https://www.dropbox.com/s/uq2pg8l28eslvd7/Screenshot%202015-05-22%2011.49.01.png?dl=0). I tried "Regular 3G" speeds with an emulation of a laptop device and was able to reproduce it with a "slower" double click.

The problem is that when the player is inserted into a more resource-heavy page, the `loadeddata` event comes slower and the probability of falling into this edge case increases.

OTOH, I was not able to reproduce it in Firefox, even with a disabled cache. No network throttling option there and I'm on a pretty fast network connection. Only the button below which simulates a quick play and then pause events works there.
