### ISSUE TITLE
clip rtmp switches not reliable in playlists

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#825]
Example: http://demos.flowplayer.org/playlist/ratio.html
`rtmp` is set correctly for every clip.
- playthrough works
- clicking on playlist items or prev/next often (not always) results in "Flash: Video not found"

I believe this is not random, but happens when you click a trigger _before_ the current video is ready, i.e. clicking next in quick sucession. Probably all these triggers must be no-ops while a clip is loading.

See also #823

**Comment by blacktrash** [comment]
This seems to be solved by https://github.com/flowplayer/flowplayer/commit/bc22032e54ae09972cdbc3c61d2ea69d96115954
@nnarhinen - you can check at http://flowplayer.blacktrash.org/fp6/ratio.html - uses assets from //cdn.834f.flowplayer.me

**Comment by nnarhinen** [comment]
I managed to break that demo when clicking randomly at the switches very fast. So there is a timing problem still. But it is such a corner case that I'm not completely sure if it makes sense to start making it 100% reliable.

The reason why it is not 100% reliable with the current code:

 * When `engine.load()` is called, the flash engine checks what rtmp is used currently by the swf object
 * If the new `clip.rtmp` differs or is not defined, the stream provider is re-initialized with new rtmp url
 * otherwise just play the new stream

So it might be that clicking randomly at the switches creates a race condition

**Comment by blacktrash** [comment]
Confirming that it still can happen with some "nasty" clicking.

**Comment by bbbo** [comment]
I think this is good enough for now. People doing nasty clicks are probably not interested in the video content anyway. Can be closed IMO and reviewed for FP7.

**Comment by blacktrash** [comment]
Agree (famous last words).
