### ISSUE TITLE
flashdisabled message does not make sense when Flash is in fact enabled

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#904]
"Adobe Flash is disabled for this page, click player area to enable" only makes sense if `!flowplayer.support.flashVideo`.
From a cursory glance at the code it probably must be more specific depending on the cirucumstances when `flashdisabled` is triggered.

**Comment by nnarhinen** [comment]
This is not true.

If you go tho chrome settings and choose in plugin options that you want to choose what plugins to run `flowplayer.support.flashVideo` is still true, even though the plugin is not loaded until the user decides to enable the plugin (by clicking the puzzle icon).

![image](https://cloud.githubusercontent.com/assets/265438/11116423/3bf1eda2-893b-11e5-9e5f-0aa9d823f3f7.png)

This is the whole purpose of `flashdisabled` event. To workaround the fact that the browser claims to have flash even though it won't run. And to run the plugins one has to click on the plugin, and we use `flashdisabled` event to bring the flash object up the visible DOM tree so that it can be directly clicked.

However, this should now behave better, as at least some of the timing issues for the timer that checks flashdisabled should be gone with ac5bf8e7c6fbf43540b4ecaa665f28b34ccee010

**Comment by blacktrash** [comment]
Ah right, I forgot about the dialog thing.
I was coming from http://demos.flowplayer.org/api/live-check.html#javascript-setup where the 'disabled' message appears on error 4 or 9 when you try to load e.g. a dummy stream in spite of Flash unconditionally enabled.
