### ISSUE TITLE
Android: HLS requires three taps to start HLS stream

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#905]
this concerns the stock Internet browser shipped with various Samsung devices, for example the Note 2 and Tab 2.

Symptom: After tapping play on the splash, a generic media player icon appears, tapping this brings back the Flowplayer play button, which will start the stream when tapped again.

See https://flowplayer.org/forum/#!/setup:need-to-click-third-to-pla

**Comment by bbbo** [comment]
see also https://flowplayer.org/forum/#!/flowplayer/setup%23flowplayer-603-and-androi

**Comment by nnarhinen** [comment]
Only HLS? or VOD too?

**Comment by nnarhinen** [comment]
@bbbo I do not have any devices left with samsung shipped stock browser. (Installed Cyagenmod on my SGS3). Is this issue still present in 6.0.4?

**Comment by bbbo** [comment]
yes. after tapping the play button, the generic media player icon appears, and you'll have to tap that, then the play button reappears and after another tap, the stream starts.
Not sure if it's worth much addo, but if you have an idea.

**Comment by nnarhinen** [comment]
This problem is not present at Galaxy Note 3 (Android 4.3) and I don't have access to any devices with older Android stock browser. The emulators at browserstack have more or less broken video playback otherwise too. Also the devices start to be kinda old and obsolete. And many use Chrome anyway.

Closing this for now, but if someone has access to such devices and wants  to fix this, pull requests are welcome.
