### ISSUE TITLE
Fullscreen events wont work in another instance

### ISSUE THREAD

**Issue by rabauss** [flowplayer/flowplayer#915]
after shutting down one instance of flowplayer commercial 6.0.2 and opening a new instance the fullscreen events wont work anymore. in chrome developer tools i can see that the event listeners *fullscreenshange are missing.

our users can then only leave fullscreen by esc-button and not with the fullscreen-close button (which wont change from open fullscreen to minimize) also the css-classes fullscreen are not set on the flowplayer-container.

is there an solution for that problem?

**Comment by blacktrash** [comment]
`shutdown()` also removes the events which must be bound to the container element, as per the docs for the method. You have to replace the container. We do not remove the container element automatically, as this might interfere with other scenarios, but that's what usually should/would happen (as per docs).
So: either *replace* the container element or double-check whether you can actually make do with `unload()` and keep the API instance. One could almost see `shutdown()` as a 'last resort' method, which is why we have to use it here: http://demos.flowplayer.org/scripting/overlay-fancybox.html (fanybox removing the element).
