### ISSUE TITLE
Flowplayer loads one fragment then stops

### ISSUE THREAD

**Issue by gburgwardt** [flowplayer/flowplayer#925]
Hello

I'm working with nginx-rtmp and bit-dash right now, but bit-dash is having some loading issues.

We'd like to try alternatives and flowplayer looks great, problem is, it only loads one fragment, then stops. Is this a known issue?

Happy to provide any help I can, not sure where to start on this one.

You can see a demo page at http://piczel.tv:8081/demo/demo.html - flowplayer is in the middle, streaming time.gov

Thanks

**Comment by blacktrash** [comment]
Thank you, especially for the demo page.
Please file issues with the [mpegdash plugin](https://github.com/flowplayer/flowplayer-mpegdash): https://github.com/flowplayer/flowplayer-mpegdash/issues. 
I see the same problem with the Dash.js player as well in your demo. In this case it's better to turn to the [Dash.js issue tracker](https://github.com/Dash-Industry-Forum/dash.js/issues) because the plugin is built on top of it..
But I think the answer is simpler: a CORS issue with your stream. This is what I see sometimes in the console:

XMLHttpRequest cannot load http://piczel.tv/dash/twots-3116834.m4v. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://piczel.tv:8081' is therefore not allowed access. The response had HTTP status code 404.

Aside: do not apply any video tag attributes in conjunction with Flowplayer, except the ones listed here: https://flowplayer.org/docs/setup.html#video-tag-attributes

Closing here.

**Comment by gburgwardt** [comment]
I updated the nginx server to allow CORS requests about an hour ago - you saw this recently?

**Comment by blacktrash** [comment]
Yes I did. Does the Dash.js player work for you? It doesn't for me[tm].
You might also be interested in https://github.com/flowplayer/flowplayer-mpegdash#debugging

**Comment by gburgwardt** [comment]
No, the dash.js player doesn't work for me either. I'll double check the CORS rules, but I don't see that in my chrome debug output (strange).

I'll take this over to the dash.js tracker if that doesn't pan out
