### ISSUE TITLE
Html5 video with flowplayer dosent  work on iPad

### ISSUE THREAD

**Issue by tako78** [flowplayer/flowplayer#929]
I use licences flowplayer, and I use html5 video in the website but the video didn't work on iPad

**Comment by blacktrash** [comment]
As the player works thousands of users on iPad, this is almost certainly a usage problem.
Therefore our public forum - https://flowplayer.org/forum/ (monitored by staff) - is your first point of call. Providing a link to a *minimal* sample page demonstrating the problem is highly recommended to increase the likelyhood of a speedy and qualified answer.
Thank you.
