### ISSUE TITLE
change live rtmp src using javascript

### ISSUE THREAD

**Issue by cherishsantosh** [flowplayer/flowplayer#975]
I have multiple live rtmp stream, on demand I am going to change rtmp src, but it not work. can any one suggest solution?

StreamURL="rtmp://xx.xxx.x.xx/oflaDemo/test1"

```html
var api = flowplayer("#player", {
    live: true,
    splash: true,
    clip: {
        sources: [
            {
                type: "application/x-mpegurl",
                src: StreamURL
            }
        ],
        title: "LiveStream"
    },
    embed: {
        skin: "http://releases.flowplayer.org/6.0.1/skin/bauhaus.css"
    }
});

```

**Comment by blacktrash** [comment]
Please use our public forum at https://flowplayer.org/forum/ for usage questions.
Normally you would not want to use an RTMP stream because Flowplayer HTML5 plays HLS also in Flash, so you have all possible clients covered, and, if you provide a variant playlist, in several resolutions/bitrates with ABR (adaptive bit rate streaming).
If for some reason you prefer RTMP over HLS where Flash is available, you must list the RTMP source before the HLS source, see the docs on picking order: https://flowplayer.org/docs/setup.html#picking-order and you must set the `rtmp` option like in this simple VOD demo: http://demos.flowplayer.org/basics/rtmp.html
But before you should ask yourself: why do I want an RTMP source?

**Comment by asanian** [comment]
I have same issue and I want to change rtmp stream src dynamically to the active speaker in my video conference. How can I do?
